-- SQLite
CREATE TABLE AUTORES
(
   IDAUTOR INTEGER PRIMARY KEY,
   AUNOMBRE CHAR(100),
   AUAPELLIDO CHAR(100),
   AUNACIONALIDAD CHAR(100),
   AUFECHANACIMIENTO CHAR(100)
);

CREATE TABLE CATEGORIAS
(
   IDCATEGORIA INTEGER PRIMARY KEY,
   CANOMBRE CHAR(40),
   CADESCRIPCION CHAR(200)
);

CREATE TABLE COMENTARIOS
(
   IDUSUARIO INTEGER NOT NULL,
   IDLIBRO INTEGER NOT NULL,
   IDCOMENTARIO INTEGER PRIMARY KEY,
   COCOMENTARIO CHAR(400),
   COVALORACION INTEGER,
   FOREIGN KEY(IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO),
   FOREIGN KEY(IDLIBRO) REFERENCES LIBROS(IDLIBRO)
);

CREATE TABLE EDITORIALES
(
   IDEDITORIAL INTEGER PRIMARY KEY,
   EDNOMBRE CHAR(100),
   EDTELEFONO INTEGER
);

CREATE TABLE EMPLEADOS
(
   IDEMPLEADO INTEGER PRIMARY KEY,
   EMNOMBRE CHAR(100),
   EMAPELLIDO CHAR(100),
   EMCORREO CHAR(100),
   EMCONTRASENA CHAR(100)
);

CREATE TABLE LIBROS
(
   IDLIBRO INTEGER PRIMARY KEY,
   IDAUTOR INTEGER,
   IDEDITORIAL INTEGER,
   IDCATEGORIA INTEGER,
   LIBTITULO CHAR(100),
   LIBDESCRIPCION CHAR(500),
   LIBISBN CHAR(20),
   LIBANOPUBLICACION INTEGER,
   LIBCANTIDAD INTEGER,
   FOREIGN KEY(IDAUTOR) REFERENCES AUTORES(IDAUTOR),
   FOREIGN KEY(IDEDITORIAL) REFERENCES EDITORIALES(IDEDITORIAL),
   FOREIGN KEY(IDCATEGORIA) REFERENCES CATEGORIAS(IDCATEGORIA)
);

CREATE TABLE MULTAS
(
   IDEMPLEADO INTEGER NOT NULL,
   IDLIBRO INTEGER NOT NULL,
   IDPRESTAMOS INTEGER NOT NULL,
   IDMULTA INTEGER PRIMARY KEY,
   MUVALOR INTEGER,
   MUFECHAGENERACION DATE,
   MUESTADO CHAR(11),
   FOREIGN KEY(IDEMPLEADO) REFERENCES EMPLEADOS(IDEMPLEADO),
   FOREIGN KEY(IDLIBRO) REFERENCES LIBROS(IDLIBRO),
   FOREIGN KEY(IDPRESTAMOS) REFERENCES PRESTAMOS(IDPRESTAMOS)
);

CREATE TABLE PERTENECE
(
   IDLIBRO INTEGER NOT NULL,
   IDCATEGORIA INTEGER NOT NULL,
   PRIMARY KEY (IDLIBRO, IDCATEGORIA),
   FOREIGN KEY(IDLIBRO) REFERENCES LIBROS(IDLIBRO),
   FOREIGN KEY(IDCATEGORIA) REFERENCES CATEGORIAS(IDCATEGORIA)
);

CREATE TABLE PRESTAMOS
(
   IDEMPLEADO INTEGER NOT NULL,
   IDLIBRO INTEGER NOT NULL,
   IDPRESTAMOS INTEGER PRIMARY KEY,
   IDUSUARIO INTEGER,
   PRFECHAPRESTAMO DATE,
   PRFECHADEVOLUCION DATE,
   PRESTADO BOOLEAN,
   FOREIGN KEY(IDEMPLEADO) REFERENCES EMPLEADOS(IDEMPLEADO),
   FOREIGN KEY(IDLIBRO) REFERENCES LIBROS(IDLIBRO),
   FOREIGN KEY(IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO)
);

CREATE TABLE RESERVAS
(
   IDRESERVA INTEGER PRIMARY KEY,
   IDLIBRO INTEGER,
   IDUSUARIO INTEGER,
   REFECHA DATE,
   FOREIGN KEY(IDLIBRO) REFERENCES LIBROS(IDLIBRO),
   FOREIGN KEY(IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO)
);

CREATE TABLE USUARIOS
(
   IDUSUARIO INTEGER PRIMARY KEY,
   USNOMBRE CHAR(100),
   USAPELLIDO CHAR(100),
   USCORREO CHAR(100),
   USCONTRASENA CHAR(100)
);
